### ISSUE TITLE
Estuary Pinning Compliance Failure: Response code on pin creation should be 200

### ISSUE THREAD

**Issue by SgtPooki** [ipfs-shipyard/pinning-service-compliance#100]
Fixing this problem will fix half of one compliance check failure: 

https://github.com/ipfs-shipyard/pinning-service-compliance/blob/d3b4334971faf4488d53025dd3714cc5bc541842/api.estuary.tech.md?plain=1#L341-L347

**Comment by en0ma** [comment]
@SgtPooki looking at https://ipfs.github.io/pinning-services-api-spec/#tag/pins/paths/~1pins/post response code should be 202
