### ISSUE TITLE
"Can delete all pins" assumes pagination works (I think)

### ISSUE THREAD

**Issue by hsanjuan** [ipfs-shipyard/pinning-service-compliance#118]
IPFS Cluster cannot properly support pagination or creation-date sorting (which is fine), but as a result, the suite also complains that not all pins can be deleted. Since pins can be deleted fine, I would prefer if it lists all pins that need to be deleted without assuming pagination works.

Also, I'm not sure, but the way is done may delete unrelated pins on a service, more than were created by the checker.

**Comment by SgtPooki** [comment]
> IPFS Cluster cannot properly support pagination or creation-date sorting (which is fine), but as a result, the suite also complains that not all pins can be deleted. Since pins can be deleted fine, I would prefer if it lists all pins that need to be deleted without assuming pagination works.

I'm not quite sure I understand this. It seems like you're trying to test against an IPFS cluster, but you're saying that pagination not being supported is causing the "delete all pins" check to fail? The deleteAllPins check *does* use pagination.. so I think I get it. `getOldestPinCreateDate` is the main function used to get the date necessary for pagination, and it is being called in `deleteAllPins.ts`:

https://github.com/ipfs-shipyard/pinning-service-compliance/blob/ace2b5771e86fe76ee44119011b202ddd2a8dc91/src/checks/delete/deleteAllPins.ts#L33-L41

Also, is it impossible for IPFS cluster to support pagination/creation-date sorting; or is it something that hasn't been implemented yet? Is there a tracking issue for this?

> Also, I'm not sure, but the way is done may delete unrelated pins on a service, more than were created by the checker.

This is a good callout, there is a silent assumption that the API keys you're using are specifically for compliance checking, but it would be a good idea to allow people to use API keys that aren't dedicated only to compliance checking.

I think if we were to solve the "delete unrelated pins" problem by keeping a list of pins created during compliance checking, and then only delete those that we have in our list, we could solve both of these problems.

What do you think?

**Comment by hsanjuan** [comment]
> I think if we were to solve the "delete unrelated pins" problem by keeping a list of pins created during compliance checking, and then only delete those that we have in our list, we could solve both of these problems

Yes, I agree that would be the best.

> Also, is it impossible for IPFS cluster to support pagination/creation-date sorting; or is it something that hasn't been implemented yet? Is there a tracking issue for this?

It is impractical. Cluster does not have a relational-database backend for storing the pins, but just a key value store. Keys don't have sorted IDs, listing keys out from this store can result in random orders. Thus some features like pagination cannot be done without reading everything to memory, sorting, etc. which is a footgun for big pinsets. I think it is ok if cluster does not support pagination. It tries to do its best and it's quite ok that it supports everything else.

**Comment by lidel** [comment]
Interesting! Let's continue in https://github.com/ipfs/pinning-services-api-spec/issues/97
