### ISSUE TITLE
Discussion: delegates and nulls

### ISSUE THREAD

**Issue by SgtPooki** [ipfs-shipyard/pinning-service-compliance#16]
hey... im going back to joi validation since it's going to make my world a lot easier, though I have to modify the Joi schema's  that are generated from the openapi spec. Anyway, i'm currently making the following modifications to the schema for a 'PinStatus' object that is returned after create:

```

const modifySchema = (schemaName: keyof PinningSpecJoiSchema, schema: JoiSchema): void => {
  switch (schemaName) {
    case 'PinStatus': {
      const namePath = ['pin', 'name']
      const nameSchema = getInnerSchema(schema, namePath)
      setInnerSchema(schema, namePath, nameSchema.allow(null))

      const originsPath = ['pin', 'origins']
      const originsSchema = getInnerSchema(schema, originsPath)
      setInnerSchema(schema, originsPath, originsSchema.allow(null))

      const metaPath = ['pin', 'meta']
      const metaSchema = getInnerSchema(schema, metaPath)
      setInnerSchema(schema, metaPath, metaSchema.allow(null))
      break
    }
    default: {
      // return schema
    }
  }
}
```

1. What do you think about those? Currently, name, origins, and meta are all OPTIONAL, and NFT.storage is returning null.. should that be within compliance? or should that actually break compliance?
2. Another validation error showing up now is: `child "delegates" fails because ["delegates" must contain at least 1 items]` and the actual value of the response is: 
```
{
  "requestid": "bafkqadjrgy2dsmzygeztmmrzgyyq",
  "status": "queued",
  "created": "2022-04-08T01:29:29.604+00:00",
  "pin": {
    "cid": "bafkqadjrgy2dsmzygeztmmrzgyyq",
    "meta": null,
    "name": null,
    "origins": null
  },
  "delegates": []
}
```

Since the pin is currently Queued.. I think we need to update the spec to allow for empty delegates unless status is Pinned. What do you think?

**Comment by lidel** [comment]
1. Created https://github.com/ipfs/pinning-services-api-spec/issues/89 – we should not allow `nulls` unless spec allows for it.
2. Delegate presence is mandatory.  Always.
  - during `queued` and`pinning` – it facilitates data transfer without the need for DHT lookup  (see [Provider hints](https://ipfs.github.io/pinning-services-api-spec/#section/Provider-hints))
  - when `pinned` –  ensures pinning service providers are good citizens. they have to provide a working multiaddr, which means they have to run bitswap-capable node. even when they fail to announce every CID on the DHT, user can check CID status, get delegate, connect to it and bitswap data back that way.
