### ISSUE TITLE
Please add Infura to the local pin services

### ISSUE THREAD

**Issue by re2005** [ipfs-shipyard/pinning-service-compliance#203]
<img width="543" alt="Screenshot 2022-09-08 at 17 06 34" src="https://user-images.githubusercontent.com/2920357/189158050-2f1abdaa-8c3b-4b16-ba2e-cc8bda7add71.png">

**Comment by SgtPooki** [comment]
@re2005 this is the wrong repo to request additions to webui, but before something can be added to webui, it needs to be added here, so... I looked into adding Infura, and they require a credit-card to set up an account, which is a blocker.

![image](https://github.com/ipfs-shipyard/pinning-service-compliance/assets/1173416/e3f034f5-13a6-4478-b72f-2ef23673c55b)


If you are from Infura, and can get us a limited account that we can use only for compliance checks, without needing a credit card, then we would be happy to add Infura to the compliance checks and webui pinning services.


closing this issue for now.
