### ISSUE TITLE
Improve UX of  pass/failed states

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/pinning-service-compliance#76]
Currently, we show ✘ and ✓ 
> ![2022-06-06_14-06](https://user-images.githubusercontent.com/157609/172157599-334bcc60-6b92-45b3-a565-343a7b970f0d.png)

@SgtPooki thoughts on making it  ❌ and 🟢? That way it will be way easier to eyeball and see what failed, even if someone is color blind (thanks to more distinct shapes)

**Comment by SgtPooki** [comment]
I don't know that those characters aren't distinct, but I will change these.

**Comment by SgtPooki** [comment]
it definitely pops more in the console with the colored emojis: 

![image](https://user-images.githubusercontent.com/1173416/172502749-baf78c7d-39af-4fa8-8112-2af5ef005d91.png)
