### ISSUE TITLE
Highlight JSON in responses

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/pinning-service-compliance#77]
@SgtPooki is  it possible to add highlighting to response sections?

> ![2022-06-06_14-14](https://user-images.githubusercontent.com/157609/172158700-a2f93165-d5cc-4e45-a4bf-dc0a54f823bb.png)

```diff
- \`\`\`
+ \`\`\`json
```

https://github.com/ipfs-shipyard/pinning-service-compliance/blob/ace2b5771e86fe76ee44119011b202ddd2a8dc91/src/output/getReportEntry.ts#L46-L52

**Comment by SgtPooki** [comment]
yea definitely. should be an easy fix.

**Comment by lidel** [comment]
Some feedback from  https://github.com/ipfs-shipyard/pinning-service-compliance/pull/68:

Single quotes produced by `inspect` break syntax highlighter for JSON:

> ![2022-06-13_20-41](https://user-images.githubusercontent.com/157609/173423778-d7cd9642-73e7-4106-929a-c1e4a448dfa2.png)

Can you check if it is possible to replace `inspect` from Nodejs `util` with  https://www.npmjs.com/package/object-inspect ?
It has `quoteStyle` and if we set it to `double`  then JSON highlighter should work correctly.
